name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macOS-latest, ubuntu-18.04, windows-latest]
        os: [ubuntu-18.04]
    steps:
      - name: Project checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: Install project dependencies
        run: yarn
      - name: Check linter
        run: yarn lint
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macOS-latest, ubuntu-18.04, windows-latest]
        os: [ubuntu-18.04, windows-latest]
    steps:
      - name: Project checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: Install project dependencies
        run: yarn
      - name: Check unit test
        run: yarn test
  # slack-workflow-status:
  #   if: always()
  #   name: slack-workflow-status
  #   needs:
  #     - linter
  #     - unit-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Status Slack notification
  #       uses: Gamesight/slack-workflow-status@master
  #       with:
  #         repo_token: ${{secrets.GITHUB_TOKEN}}
  #         slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
  #         channel: "#techflow"
  #         name: "Github Actions Bot"
  #         icon_url: "https://ca.slack-edge.com/T02DT06RF-U9WSZ7E9Y-ef460a17fb74-72"
