name: my workflow
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest,ubuntu-18.04, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: Set env vars on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          chcp 65001 #set code page to utf-8
          echo ("TAG01=" + (node -p "require('./package.json').version")) >> $env:GITHUB_ENV
          echo ("DATA_NAME=" + $secrets.DATA_NAME) >> $env:GITHUB_ENV
      - name: Set env vars on Ubuntu
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        run: |
          echo "TAG01=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "DATA_NAME=${{ secrets.DATA_NAME }}" >> $GITHUB_ENV
      - name: Test Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: echo $GITHUB_ENV
      - name: Test macOS
        if: startsWith(matrix.os, 'macOS')
        run: echo $GITHUB_ENV
      - name: Test Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          echo $env:GITHUB_ENV
