name: my workflow
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: Hardcoded tag to file
        run: |
          TAG=$(node -p "require('./package.json').version")
      - name: Set action ENV
        run: echo "TAG=$( TAG )" >> $GITHUB_ENV
      - name: Test 01
        run: echo $TAG
      - name: Test 02
        run: echo $GITHUB_ENV
