name: my workflow
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: Hardcoded tag to file
        run: echo "(node -p "require('./package.json').version")"
      - name: Set env
        run: echo "TAG=${{ cat TAG }}" >> $GITHUB_ENV
      - name: Test 02
        run: echo $GITHUB_ENV
