name: my workflow
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: Hardcoded tag to file
        run: (node -p "require('./package.json').version") > TAG
      - run: |
          chcp 65001 #set code page to utf-8
          echo ("BRANCH_NAME=" + cat TAG) >> $env:GITHUB_ENV
      - run: echo "${{ env.BRANCH_NAME }}"
      - run: echo $env:BRANCH_NAME
